<?php

namespace VA\CoreBundle\Entity;

/**
 * PlanetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanetsRepository extends BaseRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('order' => 'ASC'));
    }
}
