<?php

namespace VA\CoreBundle\Entity;

/**
 * SatellitesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SatellitesRepository extends BaseRepository
{

}
