<?php

namespace VA\CoreBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StarsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StarsRepository extends BaseRepository
{

}
