<?php

namespace VA\CoreBundle\Entity;

/**
 * SystemsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SystemsRepository extends BaseRepository
{
}
