<?php

namespace VA\CoreBundle\Entity;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends BaseRepository
{
}
